 export const genresFilter = [
   {genreName: 'Action', slug: 'action'},
   {genreName: 'Adventure', slug: 'adventure'},
   {genreName: 'Arcade', slug: 'arcade'},
   {genreName: 'Indie', slug: 'indie'},
   {genreName: 'RPG', slug: 'role-playing-games-rpg'},
   {genreName: 'Strategy', slug: 'strategy'},
   {genreName: 'Shooter', slug: 'shooter'},
   {genreName: 'Casual', slug: 'casual'},
   {genreName: 'Simulation', slug: 'simulation'},
   {genreName: 'Puzzle', slug: 'puzzle'},
   {genreName: 'Platformer', slug: 'platformer'},
   {genreName: 'Massively Multiplayer', slug: 'massively-multiplayer'},
   {genreName: 'Sports', slug: 'sports'},
   {genreName: 'Fighting', slug: 'fighting'},
   {genreName: 'Family', slug: 'family'},
   {genreName: 'Board Games', slug: 'board-games'},
   {genreName: 'Educational', slug: 'educational'},
   {genreName: 'Card', slug: 'card'}
 ]
export const platformsFilter = [
  {platformsName: 'PC' , slug: '4'},
  {platformsName: 'PlayStation5' , slug: '187'},
  {platformsName: 'PlayStation4' , slug: '18'},
  {platformsName: 'PlayStation3' , slug: '16'},
  {platformsName: 'PlayStation2' , slug: '15'},
  {platformsName: 'PlayStation' , slug: '27'},
  {platformsName: 'Xbox One' , slug: '1'},
  {platformsName: 'Xbox Series S/X' , slug: '186'},
  {platformsName: 'IOS' , slug: '3'},
  {platformsName: 'Android' , slug: '21'},
]
export const developersFilter = [
  {developersName: 'Ubisoft', slug: 'ubisoft'},
  {developersName: 'Valve Software', slug: 'valve-software'},
  {developersName: 'Feral Interactive', slug: 'feral-interactive'},
  {developersName: 'Electronic Arts', slug: 'electronic-arts'},
  {developersName: 'Ubisoft Montreal', slug: 'ubisoft-montreal'},
  {developersName: 'Sony Interactive Entertainment', slug: 'sony-interactive-entertainment'},
  {developersName: 'Square Enix', slug: 'square-enix'},
  {developersName: 'Capcom', slug: 'capcom'},
  {developersName: 'Aspyr Media', slug: 'aspyr-media'},
  {developersName: 'Bethesda Softworks', slug: 'bethesda-softworks'},
  {developersName: 'Warner Bros. Interactive', slug: 'warner-bros-interactive'},
  {developersName: 'SEGA', slug: 'sega'},
  {developersName: 'Devolver Digital', slug: 'devolver-digital'},
  {developersName: 'BANDAI NAMCO Entertainment America', slug: 'bandai-namco-entertainment-america-inc'},
  {developersName: 'Telltale Games', slug: 'telltale-games'},
  {developersName: '2K', slug: '2k'},
  {developersName: 'Capcom U.S.A', slug: 'capcom-usa-inc'},
  {developersName: 'NVIDIA Lightspeed Studios', slug: 'nvidia-lightspeed-studios'},
]
